Updates to CP2K, FHI-aims, and QE scripts

diff --git a/fhi-aims/rfhi b/fhi-aims/rfhi
--- a/fhi-aims/rfhi
+++ b/fhi-aims/rfhi
@@ -1,25 +1,24 @@
-#!/bin/bash -l
-
+#!/bin/bash
 #******************************************************#
 #                                                      #
-#             Script for running FHI-Aims              #
+#               Script for running CP2K                #
 #     Intended to work with the SLURM queue system     #
-#           within the Easley HPC system               #
+#      within the Constance/Deception HPC systems      #
 #                                                      #
 #        Benjamin Jackson, Auburn University           #
 #                 baj0040@auburn.edu                   #
 #                                                      #
-#                Updated: 04/29/2022                   #
+#                Updated: 08/18/2022                   #
 #                                                      #
 #******************************************************#
-
 Main(){
 	FNAME=$(echo ${!#} | awk -F. '{print $1}')
-  ##Defaults:
-	NODES=1
+	##Defaults:
+	TIME=8-00:00:00
 	QTYPE=g
-	TIME=200:00	
-	SCR_CLEAN=1 #Setting to autoclean FHI job folders in scratch, 1 = true
+	NODES=1
+	THREADS=1
+	SCR_CLEAN=true #Setting to autoclean FHI job folders in scratch
   ##Default paths:
 	#SUBDIR=$(pwd)
 	SUBDIR=/home/$(whoami)/.subfiles
@@ -29,156 +28,155 @@ Main(){
 	SCRIPT_PATH=$( dirname "$(readlink -f "$0")" )
 	##Modules
 	FHIAims_MODULE=fhi-aims/2021 
+
 	#Begin Program
+	if [[ "$#" -lt 1 ]]; then Helpfn; exit; fi #Calls help function if no passed variables
+	if [[ ! -e ${FNAME}.ctrl ]]; then echo "Input file was not found"; exit 30; fi
 	if [[ ! -d ${SCRDIR} ]]; then mkdir -p ${SCRDIR}; fi
 	if [[ ! -d ${BACKUPDIR} ]]; then mkdir -p ${BACKUPDIR}; fi 
-	if [[ "$#" -lt 1 ]]; then Helpfn; exit; fi #Calls help function if no passed variables
+	if [[ ${ALT_ERROR_LOCATION} = true ]]; then
+		SUBDIR=/people/$(whoami)/.subfiles;	mkdir -p ${SUBDIR}; else SUBDIR=${WRKDIR};	fi
 	Option_Handler "$@";
-	if [[ ! -e ${FNAME}.ctrl ]]; then echo "Input file was not found"; exit 30; fi
-	#Mem_Handler;
-	#Req_Check;
-	#NPROC=$(Proc_Handler)
-	Proc_Handler;
-  QUEUE=$(Queue_Set)
-	Maint_Check; #Checks if there as a max walltime and adjust time if so
-	Batch_Builder; #Construct the batch submission script
-	if [[ ${STOP} = 1 ]]; then mv ${SUBDIR}/${FNAME}.batch ${WRKDIR}/; exit; fi
+	if [[ -z ${JOBNAME} ]]; then JOBNAME=${FNAME}; fi;
+	Time_Converter;
+  Queue_Set;
+	Resources_Check;
+	#Maint_Check;
+	Batch_Builder;
+	if [[ ${STOP_MARKER} == 1 ]]; then 
+		if [[  ${SUBDIR} == ${WRKDIR} ]]; then exit;
+		else mv ${SUBDIR}/${FNAME}.batch ${WRKDIR}/; exit; fi
+	fi
 	sbatch ${SUBDIR}/${FNAME}.batch
-	#rm -f ${SUBDIR}/${FNAME}.batch
-}
-Proc_Handler(){
-  QTYPE=$( echo $QTYPE | awk '{print tolower($0)}' )
-  case ${QTYPE} in
-    [bB]2) SCALE=48; NPROC_PER=48;;
-    [rR][bB]2) SCALE=48; NPROC_PER=48;;
-    [bB]4) SCALE=48; NPROC_PER=48;;
-    [a]) SCALE=128; NPROC_PER=128;;
-    [Gg][Pp][Uu]) SCALE=48; NPROC_PER=48;;
-    [rR]) SCALE=48; NPROC_PER=48;;
-    *) SCALE=48; NPROC_PER=48;;
-  esac
-	#echo $(( ${NODES} * ${SCALE} )) 
-	NPROC=$(( ${NODES} * ${SCALE} )) 
+	rm -f ${SUBDIR}/${FNAME}.batch
 }
 Option_Handler(){
-	while getopts ":hn:c:m:t:q:g" option; do
+	while getopts ":ghen:c:m:t:q:p:rh:" option; do
 		case $option in
-			h) Helpfn; exit;;  #Call help function and exit
-			c) NPROC=$OPTARG;; #Number of Processors
-			n) NODES=$OPTARG;; #Number of Nodes
+			h) Helpfn; exit;;          #Call help function and exit
+			n) NODES_SET=$OPTARG;;     #Number of Nodes
+			c) NPROC_SET=$OPTARG;;     #Number of processors, not yet implemented fully
+			r) RESTART_OPT="true";;
 			m) MEM=$( echo $OPTARG | sed 's/GB//' );; #Memory Request
-			t) TIME=$OPTARG;;  #HOUR:MINUTES
-			q) QTYPE=$OPTARG;; #Type of Queue
-			g) STOP=1;;        #Create batch file then exit
+			t) TIME=$OPTARG;;          #HOUR:MINUTES
+			q) QTYPE=$OPTARG;;         #Define the partition 
+			h) THREADS=$OPTARG;;       #Define the number of threads
+			g) STOP_MARKER=1;;		     #Create batch file then exit; do not start job
+			e) EMAIL_MARKER=1;;        #Used to trigger email notifications
 		esac
 	done
 }
+Time_Converter(){
+ #Function for converting the time request to correct format/calculating total seconds, and job cut-off
+ #days-hours:minutes:seconds
+	if [[ ${TIME} =~ ^[[:digit:]]+$ ]]; then
+		DAY=${TIME}
+		elif [[ ${TIME} =~ ^([0-9]+)-([0-9]+):([0-9]+)(:)?([0-9]*)$ ]]; then
+			DAY=${BASH_REMATCH[1]}; HOUR=${BASH_REMATCH[2]}; MINUTE=${BASH_REMATCH[3]}; SECOND=${BASH_REMATCH[5]}
+		elif [[ ${TIME} =~ ^([0-9]+):([0-9]+)(:)?([0-9]*)$ ]]; then
+			HOUR=${BASH_REMATCH[1]}; MINUTE=${BASH_REMATCH[2]}; SECOND=${BASH_REMATCH[4]}
+		else echo "There is an error with your time specification: ${TIME}"; exit
+	fi
+	if [[ -z ${DAY} ]]; then DAY=0; fi
+	if [[ -z ${HOUR} ]]; then HOUR=0; fi
+	if [[ -z ${MINUTE} ]]; then MINUTE=0; fi
+	if [[ -z ${SECOND} ]]; then SECOND=0; fi
+	TIME_FORMAT=$( echo ${DAY}-${HOUR}:${MINUTE}:${SECOND})
+	#TIME_SEC=$(( ${DAY}*24*3600 + ${HOUR}*3600 + ${MINUTE}*60 + ${SECOND} ))
+	#TIME_SEC_SHIFT=$(( ${DAY}*24*3600 + ${HOUR}*3600 + ${MINUTE}*60 + ${SECOND} - 300 ))
+}
+Queue_Set(){
+	QTYPE=$( echo $QTYPE | awk '{print tolower($0)}' )
+	case ${QTYPE} in
+		[bB]2) NMAX=48; MEMMAX=384; QUEUE="bigmem2";;
+		[rR][bB]2) NMAX=48; MEMMAX=384; QUEUE="ezm0048_bg2";;
+		[bB]4) NMAX=48; MEMMAX=768; QUEUE="bigmem4";;
+		[Aa]) NMAX=128; MEMMAX=256; QUEUE="amd";;
+		[Aa][Mm][Dd]) NMAX=128; MEMMAX=256; QUEUE="amd";;
+		[Gg][Pp][Uu]2) NMAX=48; MEMMAX=384; QUEUE="gpu2";;
+		[Gg][Pp][Uu]4) NMAX=48; MEMMAX=768; QUEUE="gpu4";;
+		[Rr]) NMAX=48; MEMMAX=192; QUEUE="ezm0048_std";;
+		[nN]) NMAX=28; MEMMAX=125; QUEUE="nova";;
+		*) NMAX=48; MEMMAX=192; QUEUE="general";;
+	esac
+}
+Resources_Check(){
+	if [[ -n ${NODES_SET} ]] && [[ -z ${NPROC_SET} ]]; then
+		NODES=${NODES_SET}; TASK_PER_NODE=${NMAX}; NPROC=$(( ${NMAX} * ${NODES} ))  #Edit here for adding threading settings
+	elif [[ -n ${NPROC_SET} ]]; then
+	if [[ -z ${NODES_SET} ]] || [[ ${NODES_SET} == 1 ]]; then
+		NPROC=${NPROC_SET}; TASK_PER_NODE=${NPROC_SET}; NODES=1 #Edit here for adding threading settings
+			if [[ ${NPROC} -gt ${NMAX} ]]; then echo "You have requested more processors than is available on one node (${NMAX})"; exit; fi
+		elif [[ ${NODES_SET} -ne 1 ]]; then #Add functionality for specifying NPROC per nodes in this way
+			NODES=${NODES_SET}; TASK_PER_NODE=${NPROC_SET}; NPROC=$(( ${NPROC_SET} * ${NODES} ))
+		fi
+	else
+		NODES=1; NPROC=${NMAX}; TASK_PER_NODE=${NMAX}
+	fi
+}
 Batch_Builder(){
+	TAB="$(printf '\t')"
+	if [[ ${EMAIL_MARKER} == 1 ]]; then EMAIL_OPTION="#SBATCH --mail-type=END,FAIL,REQUEUE,TIME_LIMIT_90";
+		else	EMAIL_OPTION="#SBATCH --mail-type=NONE"; fi
+	if [[ ${RESTART_OPT} -ne "true" ]]; then RESTART_OPTION="#SBATCH --no-requeue"; fi
 	Opening_Gen;
 	FHIAims_Gen;
-	Closer_Gen;	
+	Closer_Gen;
 }
-#Function for specifying general job settings
+Proc_Handler(){
+#This is not currently used; add functionality for multi-threading
+	if [[ ${THREADS} == 1 ]]; then
+		:
+	fi
+}
 Opening_Gen(){
+#	Creates the opening section with Slurm settings
 	cat > ${SUBDIR}/${FNAME}.batch <<- EOF
-		#!/bin/bash -l
-		#SBATCH --job-name=${FNAME}.fhi
-		#SBATCH --error=${SUBDIR}/${FNAME}.e%j
-		#SBATCH --nodes=${NODES}
-		##SBATCH --ntasks=${NPROC}
-		#SBATCH --ntasks-per-node=${NPROC_PER}
-		#SBATCH --time=${TIME}:00
-		#SBATCH --output=/dev/null
+		#!/bin/bash  
 		#SBATCH --partition=${QUEUE}
+		#SBATCH --time=${TIME_FORMAT}
+		#SBATCH --nodes=${NODES}
+		#SBATCH --ntasks-per-node=${TASK_PER_NODE}
+		#SBATCH --cpus-per-task=${THREADS}
+		#SBATCH --job-name=${JOBNAME}.fhi
+		#SBATCH --error=${SUBDIR}/${FNAME}.err%j
+		#SBATCH --output=${SUBDIR}/${FNAME}.err%j
 		#SBATCH --mail-user=$(whoami)@auburn.edu
-		#SBATCH --mail-type=NONE
-		#SBATCH --no-requeue
-		#SBATCH --exclusive
+		${EMAIL_OPTION}
+		${RESTART_OPTION}
+		export OMP_NUM_THREADS=${THREADS}
+		ulimit -s unlimited
+		ulimit -f unlimited
+		SUBDIR=${SUBDIR}
+		SCRDIR=${SCRDIR}
 		WRKDIR=${WRKDIR}
 		FNAME=${FNAME}
-		SCRDIR=${SCRDIR}
-		SUBDIR=${SUBDIR}
 	EOF
-#${MEM_STR}
-#${NODE_STR}
-#${NPROC_STR}
-#SBATCH --cpus-per-task=1
 }
-#Function for generating FHI-Aims specific commands
 FHIAims_Gen(){
-	if [[ ${SCR_CLEAN} = 1 ]]; then rm -f ${SCRDIR}/*in; rm -f ${SCRDIR}/*out; rm -f ${SCRDIR}/band*out; rm -f ${SCRDIR}/*cube; fi
+	if [[ ${SCR_CLEAN} == "true" ]]; then rm -f ${SCRDIR}/*in; rm -f ${SCRDIR}/*out; rm -f ${SCRDIR}/band*out; rm -f ${SCRDIR}/*cube; fi
 	cat >> ${SUBDIR}/${FNAME}.batch <<- EOF
 		NPROC=${NPROC}
-		module load ${FHIAims_MODULE}
+		module -q load ${FHIAims_MODULE}
 		cp \${WRKDIR}/\${FNAME}.geom \${SCRDIR}/geometry.in
 		cp \${WRKDIR}/\${FNAME}.ctrl \${SCRDIR}/control.in
 		cd \${SCRDIR}
 		mpirun -n \${NPROC} aims.210226.scalapack.mpi.x > \${WRKDIR}/\${FNAME}.out
 		bandorg.py --IsJob --HomeDir \${WRKDIR} \${FNAME}
 		cd \${WRKDIR}
-		cube ${FNAME}.out
+		${SCRIPT_PATH}/fhicube ${FNAME}.out
 	EOF
 }
-#Cleans up error and batch files on completion
 Closer_Gen(){
 	cat >> ${SUBDIR}/${FNAME}.batch <<- EOF
-		if [[ ! -s \${SUBDIR}/\${FNAME}.e\${SLURM_JOB_ID} ]]; then
-    rm -f \${SUBDIR}/\${FNAME}.e\${SLURM_JOB_ID}; else
-    mv \${SUBDIR}/\${FNAME}.e\${SLURM_JOB_ID} \${WRKDIR}/. ; fi
+		# Clean up Script, deletes empty error files or moves to WRKDIR if not empty and the exit code
+		if [[ ! -s \${SUBDIR}/\${FNAME}.err\${SLURM_JOB_ID} ]]; then
+		${TAB} rm -f \${SUBDIR}/\${FNAME}.err\${SLURM_JOB_ID}
+		elif [[ -s \${SUBDIR}/\${FNAME}.err\${SLURM_JOB_ID} ]] && [[ \${WRKDIR} != \${SUBDIR} ]]; then
+		${TAB} mv \${SUBDIR}/\${FNAME}.err\${SLURM_JOB_ID} \${WRKDIR}/\${FNAME}.e\${SLURM_JOB_ID}
+		fi
 		exit 0
 	EOF
-}
-#Function for checking if their is a maintenance max walltime and adjusts time requests accordingly
-Maint_Check(){
-	Queue_Limit=$(/tools/scripts/max_walltime.sh | grep 'Wall-time (hours)' | awk -F: '{print $2}' | sed 's/ //') 
-	Time_Req=$( Round_Up $( echo ${TIME} | awk -F: '{print $1  * 60 +  $2 }') )
-	if [[ -s Queue_Limit ]] && [[ $(( ${Queue_Limit} * 60 )) -lt ${Time_Req} ]]; then TIME="${Queue_Limit}:00"; fi 
-}
-#Function for determing job queue
-Queue_Set(){
-	QTYPE=$( echo $QTYPE | awk '{print tolower($0)}' )
-	case ${QTYPE} in
-		[bB]2) echo "bigmem2";;
-		[rR][bB]2) echo "ezm0048_bg2";;
-		[bB]4) echo "bigmem4";;
-		[a]) echo "amd";;
-		[Gg][Pp][Uu]) echo "gpu2";;
-		[r]) echo "ezm0048_std";;
-		*) echo "general";;
-	esac
-}
-#Determines the maximum allowed resources for each queue; not currently used
-Req_Check(){
-	QTYPE=$( echo $QTYPE | awk '{print tolower($0)}' )
-	case $QTYPE in
-		rb2 | b2 ) NMAX=48; MEMMAX=384;;
-		b4) NMAX=48; MEMMAX=768;;
-		a | amd) NMAX=128; MEMMAX=256;;
-		gpu2 | gpu4) echo "This script is not set up for GPU calculations- please resubmit with another queue"; exit 30 ;;
-		s | * ) NMAX=48; MEMMAX=192;;
-	esac
-	if [[ ${NPROC} -gt ${NMAX} ]]; then NODES_NPROC=$( Div_Rounder "${NPROC}" "${NMAX}" ); fi
-	if [[ ${MEM} -gt ${MEMMAX} ]]; then NODES_MEM=$( Div_Rounder "${MEM}" "${MEMMAX}" ); fi
-	if [[ ${NODES_NPROC} -gt ${NODES_MEM} ]]; then NODES=${NODES_NPROC};
-		elif [[ ${NODES_MEM} -gt ${NODES_NPROC} ]]; then NODES=${NODES_MEM};
-		else NODES=1; fi
-	if [[ ${NODES} -eq 1 ]]; then MEM_STR="#SBATCH --mem=${MEM}GB";
-		else MEM_STR="#SBATCH --mem-per-cpu=$( Div_Rounder "${MEM}" "${NPROC}" )GB
-#SBATCH --ntasks-per-node="; 
-	fi	
-	#Set up a handler for controlling tasks per node here
-	NPROC_STR="#SBATCH --ntasks=${NPROC}"	
-	NODE_STR="#SBATCH --nodes=${NODES}"
-	if [[ ${NODE_LIMIT} -eq 1 ]]; then
-		if [[ ${MEM} -gt ${MEMMAX} ]]; then
-			echo "You have requested more memory than is available for this queue; if needed, request additional nodes"
-			exit 10
-		fi
-		if [[ $NPROC -gt $NMAX ]]; then
-			echo "You have requested more processors than is available on a node; if needed, request additional nodes"
-			exit 15
-		fi
-	fi
 }
 Helpfn(){
 echo "
@@ -211,15 +209,5 @@ EXAMPLE:
 $(echo $0) -n 12 -t 10:00 -q b2 file.ctrl 
 "
 }
-Round_Up(){
-echo $( python -c "print( int( -(-${1} // 1) ) )"   )
-}
-Div_Rounder(){
-	A=$1
-	B=$2
-	if [[ $( python -c "print(${A}%${B})" ) -ne 0 ]]; then
-		echo $( python -c "print( int( ((${A}-(${A}%${B}))/${B}+1) ) )" )
-		else echo $( python -c "print( int(${A}/${B}) )" )
-	fi
-}
 Main "$@"; exit
+
